const towtruck = {
  subTitle: {
    en: "round the clock",
    uk: "цілодобово",
  },
  title: {
    en: "LAS tow truck",
    uk: "LAS евакуатор",
  },
  preText: {
    en: "If your car breaks down for any reason, a LAS tow truck will quickly and professionally help you deliver it for repair.",
    uk: "Якщо Ваш автомобіль відмовив, з будь-якої причини, LAS евакуатор швидко та професійно допоможе доставити його на ремонт.",
  },
  firstText: {
    en: "We transport:",
    uk: "Перевозимо:",
  },
  firstList: [
    { en: "passenger cars", uk: "легкові автомобілі" },
    {
      en: "passenger cars with an open body",
      uk: "легкові автомобілі з відкритим кузовом",
    },
    { en: "offroad vehicles", uk: "позашляховики" },
    { en: "special equipment", uk: "спецтехніка" },
    {
      en: "motorcycle, moped, ATV, etc...",
      uk: "мотоцикл, мопед, квадроцикл, тощо…",
    },
  ],
  secondText: {
    en: "We suggest:",
    uk: "Пропонуємо",
  },
  secondList: [
    { en: "fast delivery", uk: "швидка подача" },
    {
      en: "24/7 operation mode",
      uk: "режим роботи 24/7",
    },
    { en: "car slippage", uk: "буксування" },
    { en: "uploading to the platform", uk: "завантаження на платформу" },
  ],
  // abouts: [
  //   {
  //     id: 0,
  //     tab1xJPG: `${tab1s0330jpg}`,
  //     tab1xWBP: `${tab1s0330wpp}`,
  //     tab2xJPG: `${tab1s0660jpg}`,
  //     tab2xWBP: `${tab1s0660wpp}`,
  //     tab3xJPG: `${tab1s0990jpg}`,
  //     tab3xWBP: `${tab1s0990wpp}`,
  //     tab4xJPG: `${tab1s1320jpg}`,
  //     tab4xWBP: `${tab1s1320wpp}`,
  //     dtp1xJPG: `${dtp1s0270jpg}`,
  //     dtp1xWBP: `${dtp1s0270wpp}`,
  //     dtp2xJPG: `${dtp1s0540jpg}`,
  //     dtp2xWBP: `${dtp1s0540wpp}`,
  //     dtp3xJPG: `${dtp1s0810jpg}`,
  //     dtp3xWBP: `${dtp1s0810wpp}`,
  //     dtp4xJPG: `${dtp1s1080jpg}`,
  //     dtp4xWBP: `${dtp1s1080wpp}`,
  //     alt: {
  //       en: "Repair of the machine chassis",
  //       uk: "Ремонт ходової частини машини",
  //     },
  //   },
  //   {
  //     id: 1,
  //     tab1xJPG: `${tab2s0330jpg}`,
  //     tab1xWBP: `${tab2s0330wpp}`,
  //     tab2xJPG: `${tab2s0660jpg}`,
  //     tab2xWBP: `${tab2s0660wpp}`,
  //     tab3xJPG: `${tab2s0990jpg}`,
  //     tab3xWBP: `${tab2s0990wpp}`,
  //     tab4xJPG: `${tab2s1320jpg}`,
  //     tab4xWBP: `${tab2s1320wpp}`,
  //     dtp1xJPG: `${dtp2s0270jpg}`,
  //     dtp1xWBP: `${dtp2s0270wpp}`,
  //     dtp2xJPG: `${dtp2s0540jpg}`,
  //     dtp2xWBP: `${dtp2s0540wpp}`,
  //     dtp3xJPG: `${dtp2s0810jpg}`,
  //     dtp3xWBP: `${dtp2s0810wpp}`,
  //     dtp4xJPG: `${dtp2s1080jpg}`,
  //     dtp4xWBP: `${dtp2s1080wpp}`,
  //     alt: {
  //       en: "Washing the machine in process",
  //       uk: "Мийка машини в процесі",
  //     },
  //   },
  //   {
  //     id: 2,
  //     tab1xJPG: `${tab3s0330jpg}`,
  //     tab1xWBP: `${tab3s0330wpp}`,
  //     tab2xJPG: `${tab3s0660jpg}`,
  //     tab2xWBP: `${tab3s0660wpp}`,
  //     tab3xJPG: `${tab3s0990jpg}`,
  //     tab3xWBP: `${tab3s0990wpp}`,
  //     tab4xJPG: `${tab3s1320jpg}`,
  //     tab4xWBP: `${tab3s1320wpp}`,
  //     dtp1xJPG: `${dtp3s0270jpg}`,
  //     dtp1xWBP: `${dtp3s0270wpp}`,
  //     dtp2xJPG: `${dtp3s0540jpg}`,
  //     dtp2xWBP: `${dtp3s0540wpp}`,
  //     dtp3xJPG: `${dtp3s0810jpg}`,
  //     dtp3xWBP: `${dtp3s0810wpp}`,
  //     dtp4xJPG: `${dtp3s1080jpg}`,
  //     dtp4xWBP: `${dtp3s1080wpp}`,
  //     alt: {
  //       en: "Car repair on the lift",
  //       uk: "Ремонт машини на підйомнику",
  //     },
  //   },
  // ],
};

export default towtruck;
